# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Swissalti3DConvert
                                 A QGIS plugin
 This plugins allows for merging several tiles of the Swissalti3D dems and convert them to anorther datum
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-29
        copyright            : (C) 2024 by Francesco Ioli
        email                : francesco.ioli@geo.uzh.ch
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Swissalti3DConvert class from file Swissalti3DConvert.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .swissalti3d_convert import Swissalti3DConvert
    return Swissalti3DConvert(iface)
